### ISSUE TITLE
No validate rules if "required" is not set and input is empty

### ISSUE THREAD

**Issue by elmelgar** [magnus-eriksson/validator#4]
If a rule has not the "required" validator and the input is empty, then the next validation may not pass. For example, if "born_at" is empty, fail:

``` php
$rules = [
'born_at' => ['integer', 'minSize:1930', 'maxSize:2000' ],
];
```

**Comment by magnus-eriksson** [comment]
You are correct. It should actually ignore all rules if it isn't required and has an empty value.
I made it so that it ignores it if the array element doesn't exist, which I realize isn't the expected behaviour.

I'll update the library as soon as my plane lands and I have access to an internet connection.

**Comment by elmelgar** [comment]
The problem now is:

``` php
$result = $validator->make(['born' => 0], ['born' => ['minSize:1930']]); // passed
$result = $validator->make(['born' => '0'], ['born' => ['minSize:1930']]); // passed
```

I can't cast the input form with:

``` php
$input = (int) $_POST['born'];
```

because $input then is the integer 0.

My be:

``` php
if (!$required && ($value === null || $value === '')) {
  return
}
```

**Comment by magnus-eriksson** [comment]
I need to think about this. 

I actually think that "Required" only should check if the array element exists or not, and not care about the content of it, at all. That's what you got the other rules for. (which means that it still was invalid before, since it checked for null).

I need to see if I need to add some extra rules to handle different cases, like allowing null, empty string, zero values etc.

If I add `$value === ""`, it would solve your issue, but it would add the same issue as yours when someone is checking strings and "minLength" instead of numbers and "minSize".

**Comment by elmelgar** [comment]
Yes, is true.

Here the implementation on Laravel, for example, is:

``` php

    protected function validateRequired($attribute, $value)
    {
        if (is_null($value)) {
            return false;
        } elseif (is_string($value) && trim($value) === '') {
            return false;
        } elseif ((is_array($value) || $value instanceof Countable) && count($value) < 1) {
            return false;
        } elseif ($value instanceof File) {
            return (string) $value->getPath() != '';
        }
        return true;
    }
```

**Comment by magnus-eriksson** [comment]
That implementation assumes that a string can't just contain spaces. I don't want to assume anything. I rather have a couple of extra rules you need to add, but then get it exactly how you like it. 

Like I said. I need to think about it. :)

**Comment by magnus-eriksson** [comment]
A new rule have been introduced in version 0.2.0.
`required` now only checks if the field exists in the data array and does not care about the contents.
The new `allowEmpty` will pass a field if it's value is evaluated as empty (using `empty($value)`.

This way, it's a bit more flexible:
```php
    // This will pass if born_at doesn't exist but fail if the value is empty
    'born_at' => ['integer', 'minSize:1930', 'maxSize:2000' ],

    // This will pass if born_at doesn't exist and if the value is empty
    'born_at' => ['allowEmpty', 'integer', 'minSize:1930', 'maxSize:2000' ],

    // This will fail if born_at doesn't exist or if the value is empty
    'born_at' => ['required', 'integer', 'minSize:1930', 'maxSize:2000' ],

    // This will fail if born_at doesn't exist but pass if the value is empty
    'born_at' => ['required', 'allowEmpty', 'integer', 'minSize:1930', 'maxSize:2000' ],
```
